### ISSUE TITLE
Trip-kit sdk not parsing near lyft vehicles (realTimeAlternativeVehicles)

### ISSUE THREAD

**Issue by danitinez** [skedgo/tripkit-ios#19]
Hi guys, @nighthawk, @MarianoTucat  I noticed that I can't get  **segment.realTimeAlternativeVehicles**, trip-kit is not parsing the Locations of those vehicles and we need them to show on the map.

I made a quick fix on the sdk but I'm not sure if it's the right solution. The issue I think is that the sdk is only parsing this information for Public Service buses and no for lyft vehicles.

Do you plan to push an update for this? Should I do a PR for my quick fix?

Thanks

**Comment by nighthawk** [comment]
Should be fixed by now.
